schema: spec-driven

context: |
  Tech stack: rust, lua, nix, markdown

rules:
  proposal:
    - Always ask questions with the questions tool.
    - Always ask questions when you are unsure about something. Never assume anything.
  design:
    - Always add/change documentation in any relevant markdown file in ./docs directory for each user facing functionality you add or change.
    - If the documentation focuses on requirements in yeet, add them under ./docs/help/ and register them accordingly.
  specs:
    - Always reference existing patterns before inventing new ones
  tasks:
    - Always break tasks into chunks of max 2 hours
    - Always run `markdownlint` for README.md and all markdown files inside ./docs to ensure your markdown files are well-formatted and follow best practices after adding or updating them.
    - Always fix any warnings or errors that `markdownlint` reports.
    - Always run `cargo test` to ensure your tests pass.
    - Always run `cargo clippy` and `cargo fmt` to ensure your code is clean and well-formatted.
    - Always fix any warnings or errors that `cargo clippy` or `cargo fmt` report.
    - Always run `git add -A && nix build .` to ensure your code tests and builds successfully.
    - Never write comments in your code. If you need to explain something, refactor the code into a function with a descriptive name instead.
